import os
import time

# for ii in range(1,36):
#     print(f"os.system('python  WebScrapping_nonmatch.py {ii}')")
#     print("time.sleep(1)")

os.system('python  WebScrapping_nonmatch.py 16 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 17 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 18 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 19 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 20 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 21 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 22 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 23 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 24 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 25 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 26 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 27 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 28 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 29 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 30 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 31 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 32 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 33 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 34 0')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 35 0')
time.sleep(1)
