import os
import time

# for ii in range(8,31):
#     print(f"os.system('python Webscrapping.py {ii}')")
#     print("time.sleep(2)")

os.system('python Webscrapping.py 8')
time.sleep(2)
os.system('python Webscrapping.py 9')
time.sleep(2)
os.system('python Webscrapping.py 10')
time.sleep(2)
os.system('python Webscrapping.py 11')
time.sleep(2)
os.system('python Webscrapping.py 12')
time.sleep(2)
os.system('python Webscrapping.py 13')
time.sleep(2)
os.system('python Webscrapping.py 14')
time.sleep(2)
os.system('python Webscrapping.py 15')
time.sleep(2)
os.system('python Webscrapping.py 16')
time.sleep(2)
os.system('python Webscrapping.py 17')
time.sleep(2)
os.system('python Webscrapping.py 18')
time.sleep(2)
os.system('python Webscrapping.py 19')
time.sleep(2)
os.system('python Webscrapping.py 20')
time.sleep(2)
os.system('python Webscrapping.py 21')
time.sleep(2)
os.system('python Webscrapping.py 22')
time.sleep(2)
os.system('python Webscrapping.py 23')
time.sleep(2)
os.system('python Webscrapping.py 24')
time.sleep(2)
os.system('python Webscrapping.py 25')
time.sleep(2)
os.system('python Webscrapping.py 26')
time.sleep(2)
os.system('python Webscrapping.py 27')
time.sleep(2)
os.system('python Webscrapping.py 28')
time.sleep(2)
os.system('python Webscrapping.py 29')
time.sleep(2)
os.system('python Webscrapping.py 30')
time.sleep(2)