import os
import time

# for ii in range(1,36):
#     print(f"os.system('python  WebScrapping_nonmatch.py {ii}')")
#     print("time.sleep(1)")

os.system('python  WebScrapping_nonmatch.py 14')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 15')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 16')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 17')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 18')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 19')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 20')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 21')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 22')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 23')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 24')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 25')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 26')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 27')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 28')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 29')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 30')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 31')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 32')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 33')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 34')
time.sleep(1)
os.system('python  WebScrapping_nonmatch.py 35')
time.sleep(1)